### ISSUE TITLE
Flickering from Bulbs?

### ISSUE THREAD

**Issue by Thesourceminer** [DaveGut/TP-Link-to-SmartThings-Integration#2]
Just wanted to leave a comment. 
Seems that the bulbs flicker when you dim. Have you seen this behavior?

**Comment by DaveGut** [comment]
Not seen it before.  If on version 3, it should not happen since it is a single command.  
Try touching to the new power setting vice dragging and see if it flickers.  You may be causing two command to send briefly.  If a LB-130, see the below link that discusses flickering.

http://forum.tp-link.com/showthread.php?95682-LB130-Flickers

**Comment by Thesourceminer** [comment]
Hey Dave is it normal for the polling to continually run (orange)
[cid:4766DF16-088D-41FA-B7C9-34C3439F35AA][cid:A6E9241D-FBF2-4D43-B122-22CF44622322]


On July 2, 2017 at 4:58:14 AM, DaveGut (notifications@github.com<mailto:notifications@github.com>) wrote:

Not seen it before. If on version 3, it should not happen since it is a single command.
Try touching to the new power setting vice dragging and see if it flickers. You may be causing two command to send briefly. If a LB-130, see the below link that discusses flickering.

http://forum.tp-link.com/showthread.php?95682-LB130-Flickers

**Comment by DaveGut** [comment]
It is not "normal", but happens when the bulb is sent a command and SmartThings doesn't process the return state.  Three possibilities
a.  Response to command is not sent to SmartThings - fairly rare.  Indicated on the Bridge console.
b.  SmartThings does not parse the return message.  Indicated by looking at the recently tab.  It should show no updates.
c.  SmartThings does not update the smartphone app color.  Go to details page.  Also look at Recently status.

Note:  I run the system as a state machine - where status is only updated when the return is parsed from the device.  This is counter to SmartThings norm of setting new status and trusting the system to work.  I do this due to having to use the Bridge (hub).

**Comment by DaveGut** [comment]
latest update.  Just tested using the SmartThings log page.  The response is sent, but SmartThings is NOT updating the phone application (android) until I switch pages.  Going from details to My Home updates.  Going from My Home to Details updates.  Hopefully this is transitory.  It has worked until today.

**Comment by Thesourceminer** [comment]
I see, interesting.
By the way thanks for this plug-in.. Its been super helpful being that TP-Link is dragging their feet on integrations outside of their platform.
I have been using Stringify, but I have noted that several variables play into completely automating a more ;-) lights on and off automatically etc..
As of last night I am just using smart things hub for it all as Stringify had too many delays.

**Comment by Thesourceminer** [comment]
So it seems that my devices keep marking themselves as inactive
However its interesting that my devices still respond if I cycle though them (on off) then the status updates.
I cannot seem to get the bridge to pull out of pulling.

**Comment by Thesourceminer** [comment]
TPLink-Bridge Device TPLink-Bridge
Name

TPLink-Bridge

Label

TPLink-Bridge

Type

TP-LinkBridge

Version

Published

Device Network Id

Bridge

Status

INACTIVE

Hub

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

Last Activity At

2017-06-30 10:15 AM PDT

Date Created

2017-06-29 8:27 PM PDT

Last Updated

2017-06-30 9:25 PM PDT

Data

No data found for device

Current States


  *   BridgeStatus<https://graph.api.smartthings.com/device/states/0fd4ad39-70bf-4058-8387-2259797fad1a?attribute=BridgeStatus>: polling
  *   ServerStatus<https://graph.api.smartthings.com/device/states/0fd4ad39-70bf-4058-8387-2259797fad1a?attribute=ServerStatus>: polling

Preferences (edit<https://graph.api.smartthings.com/device/preference?deviceId=0fd4ad39-70bf-4058-8387-2259797fad1a>)

Name

Type

Value

bridgeIP

text

10.0.5.2


Events

List Events<https://graph.api.smartthings.com/device/0fd4ad39-70bf-4058-8387-2259797fad1a/events>


Devices
Display Name

Type

Location

Hub

Zigbee Id

Device Network Id

Status

Last Activity

Bar Light 1<https://graph.api.smartthings.com/device/show/64b1ae7f-eedb-4f68-8aca-f000210dceca>

TP-Link LB100 and 110

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

BarLight1

INACTIVE

3 days ago

Bar Light 2<https://graph.api.smartthings.com/device/show/6a16695b-f786-4821-9a54-44ad9e283869>

TP-Link LB100 and 110

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

BarLight2

INACTIVE

3 days ago

Danik's iPhone<https://graph.api.smartthings.com/device/show/947e3794-afa5-487f-9cb4-6f0f9aad1a29>

Mobile Presence

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

user_uuid:aab82a80-8af3-4f6e-903c-0da20ab68b3e|89a7958b-3aa7-402d-aa06-7452ea7717e7|D46109DD-4D2B-42D1-9A7A-1738E13C30CF

ACTIVE

3 hours ago

Danikas Light<https://graph.api.smartthings.com/device/show/3b437943-142b-4ad0-a854-44e15708c7c9>

TP-Link HS Series

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

DanikaLight

INACTIVE

3 days ago

danikas room<https://graph.api.smartthings.com/device/show/db2bf8c2-1ae6-4322-9aca-0b77ffbc20ae>

SmartSense Motion Sensor

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

24FD5B00010118FC

C906

ONLINE

2 minutes ago

Dankia's Fan<https://graph.api.smartthings.com/device/show/b235b201-29f6-4dca-8dd4-740bd0dbd755>

TP-Link HS110

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

DanikaFan

INACTIVE

3 days ago

Dining Room<https://graph.api.smartthings.com/device/show/10d03e8c-2496-437c-8b53-e0f364eed9c5>

TP-Link HS Series

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

DiningRoom

INACTIVE

3 days ago

Door Light<https://graph.api.smartthings.com/device/show/7baaa3c9-f111-4c2a-ae53-e4534c045d06>

TP-Link HS Series

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

DoorLight

INACTIVE

3 days ago

Garage<https://graph.api.smartthings.com/device/show/46aa24ea-58b0-4f9e-bfcf-ff784be154c1>

SmartSense Motion Sensor

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

24FD5B000103DF1D

FD5A

ONLINE

2 minutes ago

Garage Fan<https://graph.api.smartthings.com/device/show/11032c35-14fa-47cc-b6f2-8d8d7c8f5248>

TP-Link HS110

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

GarageFan

INACTIVE

3 days ago

Garage Light<https://graph.api.smartthings.com/device/show/8aaab894-1d7f-446a-9691-666cd19a9be8>

TP-Link HS110

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

Garagelight

INACTIVE

3 days ago

Garage Light Switch<https://graph.api.smartthings.com/device/show/0e79cf58-20ac-425d-b104-27cfcbea9806>

TP-Link HS Series

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

GarageSwitch

INACTIVE

3 days ago

Home<https://graph.api.smartthings.com/device/show/78f23a27-8faa-4667-b895-1afe8dcc6955>

Ecobee Thermostat

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

e44ca708-06e3-48d9-aa3e-856a8dfa4e8b.311059093131

ONLINE

4 days ago

Kadens Fan<https://graph.api.smartthings.com/device/show/12ff5f19-9490-4631-90c5-453e10709eba>

TP-Link HS110

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

KadenFan

INACTIVE

3 days ago

Kadens Light<https://graph.api.smartthings.com/device/show/9520d63b-89f5-4079-ba20-c472fbceed04>

TP-Link HS110

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

KadenLight

INACTIVE

3 days ago

kadens room<https://graph.api.smartthings.com/device/show/ea25327f-0f39-4c0d-880e-866bb26d9ab8>

SmartSense Motion Sensor

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

24FD5B0001010D16

D8A2

ONLINE

a minute ago

Kevin's iPhone<https://graph.api.smartthings.com/device/show/b3eb6061-dba2-439f-a07c-276662c815dc>

Mobile Presence

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

user_uuid:fc90d7d7-7fa9-46d5-b40c-5b23b0bb0733|89a7958b-3aa7-402d-aa06-7452ea7717e7|4E278B75-104F-45E2-AD10-14AE51BD584E

ACTIVE

2 hours ago

Kitchen<https://graph.api.smartthings.com/device/show/dfe1bb7b-c2f2-4147-acd6-906cb3ad7b38>

SmartSense Motion Sensor

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

24FD5B000103DEFB

61BB

ONLINE

a few seconds ago

Kitchen Lights<https://graph.api.smartthings.com/device/show/3b1caa5a-d6ff-47c6-9b7e-818720eaaf3f>

TP-Link HS Series

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

KitchenLight

INACTIVE

3 days ago

Living Room 1<https://graph.api.smartthings.com/device/show/0385ee9a-af79-4fbf-a055-324235f4e177>

TP-Link LB120

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

LivingRoom1

INACTIVE

3 days ago

Living Room 2<https://graph.api.smartthings.com/device/show/1a0c9b64-d99b-4204-a6b6-b774a0c89465>

TP-Link LB100 and 110

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

LivingRoom2

INACTIVE

3 days ago

livingroom<https://graph.api.smartthings.com/device/show/eaf6f7ef-6f7b-4b0d-91f7-5558758e0eb0>

SmartSense Motion Sensor

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

24FD5B0001004E3E

3BFE

ONLINE

a few seconds ago

Master Fan<https://graph.api.smartthings.com/device/show/e21cfa06-ac12-4ee1-8c14-cdb15be54036>

TP-Link HS Series

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

MasterFan

INACTIVE

3 days ago

TPLink-Bridge<https://graph.api.smartthings.com/device/show/0fd4ad39-70bf-4058-8387-2259797fad1a>

TP-LinkBridge

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

Home Hub<https://graph.api.smartthings.com/hub/show/49b19900-3f3d-4d5f-b462-b81f0f4f6c0a>

Bridge

INACTIVE

3 days ago

Upstairs<https://graph.api.smartthings.com/device/show/ed027da7-fc19-499d-8d70-bd5510b51e06>

Ecobee Sensor

Home<https://graph.api.smartthings.com/location/show/89a7958b-3aa7-402d-aa06-7452ea7717e7>

ecobee_sensor-rs:100-CTL9

INACTIVE

3 days ago

**Comment by DaveGut** [comment]
1.  Before recycling are the devices responding to on/off commands?  I sometimes get the inactive status and just poll or turn on/off.  Do not know why.  It is generated in Smart Things.

2.  I think you added or made changes to some code to increase polling.  What is the exact current wording"  (If you did this wrong, it could cause the inactive status by SmartThings due to too much activity.)

Bridge Polling will continue per the refresh command every 15 minutes.

**Comment by Thesourceminer** [comment]
So it looks like in version 3 the bridge is not needed? I removed it updated the devices and they are more stable


On July 4, 2017 at 6:33:10 AM, DaveGut (notifications@github.com<mailto:notifications@github.com>) wrote:

  1.  Before recycling are the devices responding to on/off commands? I sometimes get the inactive status and just poll or turn on/off. Do not know why. It is generated in Smart Things.

  2.  I think you added or made changes to some code to increase polling. What is the exact current wording" (If you did this wrong, it could cause the inactive status by SmartThings due to too much activity.)

Bridge Polling will continue per the refresh command every 15 minutes.

**Comment by DaveGut** [comment]
Correct.  The bridge device handler is optional.  Never caused problems; however.....
Thanks for the feedback.  I will close this on Friday if no further comments.

By the way - do you use the HS110 Device Handler with Emeter Functions??  If so, how does it look/work.  I used the LB120 / LB130 bulbs with emeter and had one tester.

**Comment by Thesourceminer** [comment]
You know I have not actually seen a use for it. However it does seem to report Energy status.

**Comment by Thesourceminer** [comment]
[cid:739E9743-8C4E-4162-8A0D-749648B264A1]


On July 4, 2017 at 2:15:39 PM, Kevin Carlson (kevin@thecarlsons.us<mailto:kevin@thecarlsons.us>) wrote:

You know I have not actually seen a use for it. However it does seem to report Energy status.

**Comment by DaveGut** [comment]
Issue closed.  No corrective action at this time:
1.  Bulb flicker is TP-Link issue.
2.  Long period in waiting has been noticed to be occasional SmartThing issue:
     a.  Command response received and parsed per SmartThings Log.
     b.  No update sent to device current page.
     c.  Changing pages updates app status.
